### ISSUE TITLE
Metrics coming out of API 

### ISSUE THREAD

**Issue by robcxyz** [geometry-labs/icon-governance#17]
Per title, somehow metrics from the governance-worker-cron were being leaked into the load balancer. For now metrics are disabled on the cron but we should figure this out as we need alarms on those crons.

**Comment by shinyfoil** [comment]
Trying to make the selector labels in the services more specific so only API pods are being picked up in the service definition. We'll see if this fixes it in dev before deploying fix to prod.

**Comment by shinyfoil** [comment]
Ahhh, it's a service mesh misconfiguration. The worker is being added to the mesh to have access to the ICON nodes, but it's also injecting itself as the same service as the API pods. For now, we will just disable the mesh injection on the workers and just use the cluster DNS to access ICON nodes.
